# Generated by Django 3.2.3 on 2021-07-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_youtube_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='youtube_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='YouTube video url'),
        ),
    ]
